name: mano
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.8.1
  uuid: ^4.5.1
  rxdart: ^0.27.7
  image_picker: ^1.2.1
  image_gallery_saver_plus: ^4.0.1
  http: ^1.2.2
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ✅ إضافة الباكدج الخاصة باللوجو
  flutter_launcher_icons: ^0.13.1

# ✅ إعدادات اللوجو
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # 👈 حط هنا صورة اللوجو

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
          weight: 700
